services:
  web:
    build: .
    expose:
      - "5000:5000"
    depends_on:
      - mariadb
    networks:
      - trabajo1
    deploy:
      replicas: 4

  mariadb:
    image: mariadb
    restart: always
    expose:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wolfxyz
      MYSQL_PASSWORD: wolfxyz
      MYSQL_DATABASE: ipmd
    networks:
      - trabajo1

  adminer:
    image: adminer
    restart: always
    expose:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    networks:
      - trabajo1

  prometheus:
    image: prom/prometheus
    container_name: "prometheus"
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - trabajo1

  grafana:
    image: grafana/grafana
    container_name: "grafana"
    restart: always
    ports:
      - "3000:3000"
    networks:
      - trabajo1
    volumes:
      - grafana-storage:/var/lib/grafana
      
  nginx:
    image: nginx:latest
    container_name: "nginx"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    expose:
      - "80:80"
    depends_on:
      - web

networks:
  trabajo1:
    name: Trabajo1-network
    driver: bridge

volumes:
  grafana-storage:
