services:
  web:
    container_name: "flask"
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mariadb

  mariadb:
    container_name: "mariadb"
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    environment:
        MYSQL_ROOT_PASSWORD: root      
        MYSQL_USER: wolfxyz
        MYSQL_PASSWORD: wolfxyz
        MYSQL_DATABASE: ipmd

  adminer:
    container_name: "adminer"
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
 
networks:
  default: 
    name: Trabajo1-network
