services:
  web:
    build: .
    expose:
      - "5000"
    depends_on:
      - mariadb
    deploy:
      mode: replicated
      replicas: 4
    networks:
        - trabajo1

  mariadb:
    image: mariadb
    container_name: "mariadb"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wolfxyz
      MYSQL_PASSWORD: wolfxyz
      MYSQL_DATABASE: ipmd
    networks:
      - trabajo1

  adminer:
    image: adminer
    container_name: "adminer"
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    networks:
      - trabajo1

  prometheus:
    image: prom/prometheus
    container_name: "prometheus"
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - trabajo1

  grafana:
    image: grafana/grafana
    container_name: "grafana"
    restart: always
    ports:
      - "3000:3000"
    networks:
       - trabajo1
    volumes:
      - grafana-storage:/var/lib/grafana

  mysqld-exporter:
      image: quay.io/prometheus/mysqld-exporter
      container_name: "mysqld-exporter"
      restart: always
      ports:
        - "9104:9104"
      command:
        - "--config.my-cnf=/etc/.my.cnf"
        - "--mysqld.address=mariadb:3306"
      volumes:
        - ./config.my-cnf:/etc/.my.cnf
      extra_hosts:
        - "mysqld-exporter:127.0.0.1"
      networks:
        - trabajo1

  nginx:
    image: nginx:latest
    container_name: "nginx"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - trabajo1

networks:
  trabajo1:
    name: trabajo1
    driver: bridge

volumes:
  grafana-storage:
