services:
  web:
    build: .
    expose:
      - "5000:5000"
    depends_on:
      - mariadb
    deploy:
      replicas: 4

  mariadb:
    image: mariadb
    restart: always
    expose:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    environment:
        MYSQL_ROOT_PASSWORD: root      
        MYSQL_USER: wolfxyz
        MYSQL_PASSWORD: wolfxyz
        MYSQL_DATABASE: ipmd

  adminer:
    image: adminer
    restart: always
    expose:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mariadb

  nginx:
    image: nginx:latest
    container_name: "nginx"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    expose:
      - "80:80"
    depends_on:
      - web

networks:
  loadbalancing:

  default: 
    name: trabajo1-network
