global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'flask'
    static_configs:
      - targets: ['web:5000']

  - job_name: 'mariadb'
    static_configs:
      - targets: ['localhost:3306']
    

  - job_name: 'mysqld-exporter'
    static_configs:
      - targets: ['localhost:9104']

