global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'flask'
    static_configs:
      - targets: ['flask:5000']

  - job_name: 'mariadb'
    static_configs:
      - targets: ['mariadb:3306']


