services:
  namenode:
    # image: apache/hadoop:3
    build:
      context: .
      dockerfile: namenode/Dockerfile
    hostname: namenode
    container_name: namenode
    ports:
      - 9870:9870
    command: ["hdfs", "namenode"]
    env_file:
      - ./config
    volumes:
      - ./userdata:/userdata
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
  datanode_1:
    image: apache/hadoop:3
    container_name: datanode-1
    command: [ "hdfs", "datanode" ]
    env_file:
      - ./config
  datanode_2:
    image: apache/hadoop:3
    container_name: datanode-2
    command: [ "hdfs", "datanode" ]
    env_file:
      - ./config

  # resourcemanager:
  #   image: apache/hadoop:3
  #   hostname: resourcemanager
  #   command: [ "yarn", "resourcemanager" ]
  #   ports:
  #     - 8088:8088
  #   env_file:
  #     - ./config
  #   volumes:
  #     - ./test.sh:/opt/test.sh
  # nodemanager:
  #   image: apache/hadoop:3
  #   command: [ "yarn", "nodemanager" ]
  #   env_file:
  #     - ./config
