services:
  namenode:
    image: bde2020/hadoop-namenode:latest
    container_name: namenode
    environment:
      - CLUSTER_NAME=test_cluster
    ports:
      - "9870:9870"

  datanode:
    image: bde2020/hadoop-datanode:latest
    container_name: datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    depends_on:
      - namenode
    ports:
      - "9864:9864"

  hive-server:
    image: bde2020/hive:latest
    container_name: hive-server
    environment:
      - HIVE_MODE=server
      - SERVICE_NAME=hiveserver2
    depends_on:
      - namenode
      - datanode
    ports:
      - "10000:10000"
      - "10002:10002"
    volumes:
      - ./data:/data
      
  mariadb:
    image: mariadb
    container_name: "mariadb"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wolfxyz
      MYSQL_PASSWORD: wolfxyz
      MYSQL_DATABASE: ipmd
  
  grafana:
    image: grafana/grafana
    container_name: "grafana"
    restart: always
    ports:
      - "3000:3000"

