services:
  namenode:
    # image: apache/hadoop:3
    build:
      context: .
      dockerfile: namenode/Dockerfile
    hostname: namenode
    container_name: namenode
    ports:
      - 9870:9870
    command: ["hdfs", "namenode"]
    env_file:
      - ./config
    volumes:
      - ./userdata:/userdata
      - ./estructura:/estructura
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
    networks:
      mynet:
        ipv4_address: 172.18.0.2

  datanode_1:
    image: apache/hadoop:3
    container_name: datanode-1
    command: [ "hdfs", "datanode" ]
    env_file:
      - ./config
    networks:
      - mynet

  datanode_2:
    image: apache/hadoop:3
    container_name: datanode-2
    command: [ "hdfs", "datanode" ]
    env_file:
      - ./config
    networks:
      - mynet

  hive:
    build:
      context: .
      dockerfile: hive/Dockerfile
    container_name: hive-server
    environment:
      - SERVICE_NAME=hiveserver2
    depends_on:
      - namenode
    ports:
      - "10000:10000"
      - "10002:10002"
    volumes:
      - ./hive:/hive
    networks:
      - mynet

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql  
      - ./db:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wolfxyz
      MYSQL_PASSWORD: wolfxyz
      MYSQL_DATABASE: ipmd
    networks:
      - mynet
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana  
    networks:
      - mynet
  
  ejecutor:
    build:
      context: .
      dockerfile: ejecutor/Dockerfile
    container_name: ejecutor
    volumes:
      - ./userdata:/userdata
      - ./estructura:/estructura
    networks:
      - mynet

networks:
  mynet:
    name: mynet
    driver: bridge

volumes:
  mariadb_data:      
  grafana-storage:  
